### ISSUE TITLE
Switch to OpenWPM

### ISSUE THREAD

**Issue by aruneshmathur** [aruneshmathur/dark-patterns#12]
@gunesacar and I discussed that we should to move away from vanilla Selenium and integrate our crawler with OpenWPM.

OpenWPM has several logging capabilities that may be of use to us in the long term (e.g., HTTP logging to determine requests that correspond to the Dark Patterns we discover).

**Comment by gunesacar** [comment]
OK, I added OpenWPM as a submodule: https://github.com/aruneshmathur/dark-patterns/tree/master/src/crawler

I'll work on integrating existing crawler code to OpenWPM.

**Comment by gunesacar** [comment]
Actually, we don't need to port the existing link extraction crawler. I will rather start a fresh crawler for the flow/interaction/mutation observer code.

**Comment by gunesacar** [comment]
Here is a placeholder function. @aruneshmathur  you can use `self.driver ` to interact with the page:
https://github.com/gunesacar/OpenWPM/commit/de6d63010be3d977241e8f1d5c28fc749a1a409f

**Comment by gunesacar** [comment]
We've already integrated a content script (mutation summary) and a template custom function as an example. We can follow those examples to integrate segmenting, clustering and page interaction code.

@aruneshmathur let me know if you need my help with this.

**Comment by aruneshmathur** [comment]
Thanks! I'm closing this.
