### ISSUE TITLE
Reducing overhead in segmentation

### ISSUE THREAD

**Issue by aruneshmathur** [aruneshmathur/dark-patterns#18]
@gunesacar pointed out that our [segmentation algorithm](https://github.com/aruneshmathur/dark-patterns/blob/master/src/crawler/segment.js) makes repeated calls to `getBoundingClientRect()` for element width/height. This function call is expensive and adds significant overhead.

We need to avoid making repeated calls to `getBoundingClientRect()`, and reuse its output where we can.

**Comment by gunesacar** [comment]
(new) Segmentation took 1038 ms
(old) Basic segmentation took 6 ms

**Comment by aruneshmathur** [comment]
I'll try to optimize the calls as you suggested.

**Comment by aruneshmathur** [comment]
Should be much faster with the latest update. Tested on Firefox 52 ESR.

**Comment by aruneshmathur** [comment]
@gunesacar Safe to say this is reasonable now?
