### ISSUE TITLE
Handle cases where computed style is null

### ISSUE THREAD

**Issue by gunesacar** [aruneshmathur/dark-patterns#25]
[This call](https://github.com/aruneshmathur/dark-patterns/blob/master/src/crawler/common.js#L243) to `getComputedStyle` in common.js returns `null` in some cases and causes and error.

I tried to see if there's something wrong with our instrumentation, but Firefox devtools itself cannot find any style info for these elements:

![screenshot_2018-11-28_19-10-55](https://user-images.githubusercontent.com/5788790/49245577-c188ec00-f3e0-11e8-8495-7cfb7e236837.png)

Let's handle these cases.

**Comment by gunesacar** [comment]
This shouldn't be a bug in devtools; that wouldn't explain why `getComputedStyle` returns `null`, right?
xpath: `//*[@id="player"]`

**Comment by aruneshmathur** [comment]
Oops, I misread your earlier comment. Yes, this works fine - thanks!
